### ISSUE TITLE
error on data import

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#32]
```
root@LAPTOP-E0HT1CM9:~/rides-blueprint# source postgres.sh
Traceback (most recent call last):
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/pg8000/legacy.py", line 249, in execute
    self._context = self._c.execute_unnamed(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/pg8000/core.py", line 673, in execute_unnamed
    self.handle_messages(context)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/pg8000/core.py", line 810, in handle_messages
    raise self.error
pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(9)', 'F': 'varchar.c', 'L': '633', 'R': 'varchar'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/pg8000/legacy.py", line 274, in execute
    raise cls(msg)
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(9)', 'F': 'varchar.c', 'L': '633', 'R': 'varchar'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 216, in <module>
    cli()
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 111, in read_raw_data
    result = import_jsons(directory, region_name, engine)
  File "/root/rides-blueprint/src/rider/files.py", line 120, in import_jsons
    return populate_raw_table(json_list, region_name, engine)
  File "/root/rides-blueprint/src/rider/files.py", line 113, in populate_raw_table
    conn.execute(stmt)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/root/rides-blueprint/.venv/lib/python3.8/site-packages/pg8000/legacy.py", line 274, in execute
    raise cls(msg)
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(9)', 'F': 'varchar.c', 'L': '633', 'R': 'varchar'}
[SQL: INSERT INTO jsondata (external_waybill_id, external_customer_id, external_vehicle_id, external_vehicle_type_id, cargo_type, customer_title, start_date, start_date_plan, end_date, end_date_plan, start_epoch, end_epoch, vehicle_reg_num, vehicle_type_title, waybill_number, data, added, region_name) VALUES (%s, %s, %s, %s, %s, %s, NULL, %s, NULL, %s, %s, %s, %s, %s, %s, %s, now(), %s)]
[parameters: ('0057e2c2-6ac9-11eb-914f-c4346bc03f7c', 'ef8c0f17-419d-11e5-80bc-1cc1de769e18', '47e1c507-1e3d-4927-9ed0-6e2a71dee4ee', '0cbfee4e-e837-11e4-8259-448a5b240ce9', 'CG', 'ДИ (Дирекция инфраструктуры)', datetime.datetime(2021, 2, 10, 4, 0, tzinfo=tzutc()), datetime.datetime(2021, 2, 10, 13, 0, tzinfo=tzutc()), 1612926747, 1612965596, 'В 628 ТХ 64', 'Грузовой\\Самосвал', 'СРТ729180', '[{"x": 46.886808, "y": 52.148608, "z": 50, "s": 0, "c": 0, "sc": 10, "t": 1612926747}, {"x": 46.886808, "y": 52.148608, "z": 50, "s": 0, "c": 0, "sc" ... (216212 characters truncated) ... 488, "z": 105, "s": 64, "c": 98, "sc": 12, "t": 1612965578}, {"x": 46.328352, "y": 51.822056, "z": 115, "s": 66, "c": 98, "sc": 12, "t": 1612965596}]', 'volga')]
(Background on this error at: http://sqlalche.me/e/14/f405)
root@LAPTOP-E0HT1CM9:~/rides-blueprint# 
```

**Comment by epogrebnyak** [comment]
this is `poetry run python manage.py read-raw-data --region-name volga --directory ./data_sample_large --db-url postgresql+pg8000://scott:tiger@localhost:5432/rider_db`
